- package.json
- samples/package.json
Release notes forthcoming in the next comment.
> Bump version to 1.1.0

- samples/system-test/translate.test.js
> Linting per prettier@1.9.0.

- system-test/translate.ts
- test/index.ts
deepEqual is deprecated. Use deepStrictEqual instead
> chore: assert.deelEqual => assert.deepStrictEqual

- CHANGELOG.md
- package.json
> Release nodejs-translate v2.0.0

- CHANGELOG.md
- package.json
- samples/package.json
> Release nodejs-translate v2.1.0

- CHANGELOG.md
- package.json
> Release nodejs-translate v2.1.1

- test/index.ts
- tsconfig.json
> Enable noImplicitThis in tsconfig

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/translate v2.1.2

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/translate v2.1.3

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/translate v2.1.4

- .gitignore
- package.json
- protos/google/cloud/translate/v3beta1/translation_service.proto
- src/index.ts
- src/v2/index.ts
- src/v3beta1/.eslintrc.yml
- src/v3beta1/doc/google/cloud/translation/v3beta1/doc_translation_service.js
- src/v3beta1/doc/google/longrunning/doc_operations.js
- src/v3beta1/doc/google/protobuf/doc_any.js
- src/v3beta1/doc/google/protobuf/doc_timestamp.js
- src/v3beta1/doc/google/rpc/doc_status.js
- src/v3beta1/index.js
- src/v3beta1/translation_service_client.js
- src/v3beta1/translation_service_client_config.json
- synth.metadata
- synth.py
- test/.eslintrc.yml
- test/gapic-v3beta1.js
- test/index.ts
BREAKING CHANGE:  Although I don't believe existing users on v2 will experience a breaking change, we also DID bundle some gRPC dependencies and a new gapic library. I feel this warrants a major bump. @JustinBeckwith any thoughts?
> feat: add version v3beta1

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/translate v3.0.0

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/translate v3.0.1

- package.json
- src/v2/index.ts
- test/index.ts
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
> feat: support apiEndpoint override

- package.json
> fix(deps): drop unused dependency lodash.merge, related to sec vulnerability (fixes #301)

- samples/test/v3beta1/translate_translate_text_beta.test.js
Fix to the test causing problems for #306
> fix: Update test with improved translation

- samples/v3beta1/translate_batch_translate_text_beta.js
Fixes an internally filed issue. [*](b/130803258)
> fix(samples): use us-central1 region (not global)

- samples/quickstart.js
> fix: Remove extra brace in snippet

- samples/v3/translate_translate_text_with_model.js
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
> fix: region tag

- .nycrc
- README.md
> docs: update samples in the readme

- synth.metadata
- synth.py
update from reference:
googleapis/gapic-generator-typescript#134
> chore: update synth.py to pass package name

- samples/v3/translate_batch_translate_text.js
- samples/v3/translate_batch_translate_text_with_glossary.js
- samples/v3/translate_batch_translate_text_with_glossary_and_model.js
- samples/v3/translate_batch_translate_text_with_model.js
- samples/v3/translate_create_glossary.js
- samples/v3/translate_delete_glossary.js
- samples/v3/translate_detect_language.js
- samples/v3/translate_get_glossary.js
- samples/v3/translate_get_supported_languages.js
- samples/v3/translate_get_supported_languages_for_target.js
- samples/v3/translate_list_codes.js
- samples/v3/translate_list_glossary.js
- samples/v3/translate_list_language_names.js
- samples/v3/translate_translate_text.js
- samples/v3/translate_translate_text_with_glossary.js
- samples/v3/translate_translate_text_with_glossary_and_model.js
- samples/v3/translate_translate_text_with_model.js
Fixes [b/146371267
](146371267)
The motivation for this involves suppressing unhandled promise rejection errors that may arise from the translate APIs. These errors are inherently noisy and not necessarily helpful when it comes to debugging features of our APIs.
> fix: suppress unhandled promise rejection errors

- .bots/header-checker-lint.json
- .clang-format
> chore: remove header check ignore and clang

- samples/test/quickstart.test.js
> test: translation of text added comma

- samples/automl/automlTranslationDataset.js
> fix(samples): typo in CLI invocation

- samples/test/v3beta1/translate_list_glossary_beta.test.js
> test: ensure glossaryId in sample tests is unique
